[tool.black]
line-length = 100
target-version = ["py310"]
exclude = '''
/(
    \.venv
  | build
  | dist
  | csv
  | fixtures
)/
'''

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
  ".venv",
  "build",
  "dist",
  "csv",
  "fixtures"
]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes (unused imports, vars)
  "I",   # import sorting
  "UP",  # pyupgrade
  "B",   # bugbear
]

ignore = [
  "E501",   # line length (black handles it)
]

fixable = ["ALL"]

[tool.ruff.lint.isort]
combine-as-imports = true
